In [77]:
import numpy as np
import scipy.linalg as lin

arr = np.array([1, 2, 3, 4, 5])

In [78]:
np.ndim(arr)

1

In [79]:
arr.size

5

In [80]:
arr.shape

(5,)

In [81]:
arr.shape[0]

5

In [82]:
arr2 = np.array([[1.,2.,3.], [4.,5.,6.]])

In [83]:
arr2.shape

(2, 3)

In [84]:
arr2.shape[0]

2

In [85]:
arr2.shape[1]

3

In [86]:
a = np.array([1.,2.,3.])
b = np.array([2.,3.,4.])
c = np.array([3.,4.,5.])
d = np.array([4.,5.,6.])

np.block([[a,b],[c,d]])

array([[1., 2., 3., 2., 3., 4.],
       [3., 4., 5., 4., 5., 6.]])

In [87]:
a[-1]

3.0

In [88]:
a[1:2]

array([2.])

In [89]:
a = np.array([[1.,2.,3.], [4.,5.,6.]])
a[1,:]

array([4., 5., 6.])

In [90]:
a[1]

array([4., 5., 6.])

In [91]:
a[np.ix_([0],[0])]

array([[1.]])

In [92]:
a[::2, :]

array([[1., 2., 3.]])

In [93]:
a[::-1,:]

array([[4., 5., 6.],
       [1., 2., 3.]])

In [94]:
a[np.r_[:len(a),0]]

array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [95]:
a.transpose()

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [96]:
a.conj().transpose()

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [97]:
a @ b

array([20., 47.])

In [98]:
a * b

array([[ 2.,  6., 12.],
       [ 8., 15., 24.]])

In [99]:
a / b

array([[0.5       , 0.66666667, 0.75      ],
       [2.        , 1.66666667, 1.5       ]])

In [100]:
a ** 3

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [101]:
(a>4)

array([[False, False, False],
       [False,  True,  True]])

In [102]:
np.nonzero(a>4)

(array([1, 1]), array([1, 2]))

In [103]:
a[a<0.5] = 0


In [104]:
a * (a > 0.5)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [105]:
a[:] = 3

In [106]:
a

array([[3., 3., 3.],
       [3., 3., 3.]])

In [107]:
b = a.copy()

In [108]:
a, b

(array([[3., 3., 3.],
        [3., 3., 3.]]), array([[3., 3., 3.],
        [3., 3., 3.]]))

In [109]:
b = a[1,:].copy()
b

array([3., 3., 3.])

In [110]:
b = a.flatten()
b

array([3., 3., 3., 3., 3., 3.])

In [111]:
np.arange(1., 11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [112]:
np.r_[1.,11.]

array([ 1., 11.])

In [113]:
np.r_[:9:10j]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [114]:
np.arange(1., 11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [115]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [117]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [118]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
np.diag(a)

array([3., 3.])

In [120]:
np.diag(a,0)

array([3., 3.])

In [121]:
np.random.rand(3,4)

array([[0.02885798, 0.81514969, 0.30633332, 0.89224563],
       [0.69918228, 0.25496823, 0.54694707, 0.93688278],
       [0.32534622, 0.70781711, 0.56265294, 0.02354934]])

In [122]:
np.random.random_sample((3,4,5))

array([[[0.36694538, 0.66504411, 0.70327225, 0.28516201, 0.23881544],
        [0.42491971, 0.77419494, 0.14380848, 0.58137766, 0.40036163],
        [0.80925561, 0.70093503, 0.30007779, 0.72887555, 0.91544235],
        [0.44889917, 0.70750121, 0.79849084, 0.97091002, 0.35815023]],

       [[0.31928523, 0.93497531, 0.15261098, 0.26792632, 0.65725439],
        [0.0262446 , 0.45249858, 0.37781588, 0.11713067, 0.60844693],
        [0.96702969, 0.33587198, 0.13721132, 0.49404352, 0.67075884],
        [0.27825107, 0.66223728, 0.49095671, 0.23360148, 0.84535181]],

       [[0.98962137, 0.0204713 , 0.84822299, 0.87259641, 0.9731774 ],
        [0.74219646, 0.31161604, 0.27841527, 0.1530569 , 0.93864764],
        [0.50819815, 0.75152459, 0.25616062, 0.67425486, 0.62959948],
        [0.17888983, 0.85711686, 0.00230169, 0.91244083, 0.54788751]]])

In [123]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [124]:
np.mgrid[0:9., 0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [125]:
np.ogrid[0:9., 0:6.]

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]])]

In [126]:
np.ix_(np.r_[0:9.], np.r_[0:6.])

(array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]]))

In [127]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]), array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [128]:
np.tile(a, (3,4))

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [129]:
np.concatenate((c,d),0)

array([3., 4., 5., 4., 5., 6.])

In [130]:
np.vstack((c,d))

array([[3., 4., 5.],
       [4., 5., 6.]])

In [131]:
d.max()

6.0

In [132]:
d.max(0)

6.0

In [133]:
a.max(1)

array([3., 3.])

In [134]:
np.maximum(c,d )

array([4., 5., 6.])

In [135]:
np.sqrt(c @ c)

7.0710678118654755

In [136]:
np.linalg.norm(c)

7.0710678118654755

In [137]:
np.logical_and(c,d)

array([ True,  True,  True])

In [138]:
np.logical_or(c,d)

array([ True,  True,  True])

In [139]:
a = np.array([[1, 2, 3], [4,5,6], [7,10,9]])

lin.eig(a)

(array([16.82540654+0.j, -0.56655283+0.j, -1.2588537 +0.j]),
 array([[-0.22187905, -0.86720234, -0.7307057 ],
        [-0.49983984,  0.47988984, -0.16747068],
        [-0.83721552,  0.13291287,  0.66183288]]))

In [140]:
lin.inv(a)

array([[-1.25      ,  1.        , -0.25      ],
       [ 0.5       , -1.        ,  0.5       ],
       [ 0.41666667,  0.33333333, -0.25      ]])

In [141]:
lin.pinv(a)

array([[-1.25      ,  1.        , -0.25      ],
       [ 0.5       , -1.        ,  0.5       ],
       [ 0.41666667,  0.33333333, -0.25      ]])

In [142]:
lin.solve(a, c)

array([-1.        , -0.        ,  1.33333333])

In [143]:
lin.svd(a)

(array([[-0.20157473, -0.72595537, -0.65753816],
        [-0.48945851, -0.50683053,  0.70961481],
        [-0.8484091 ,  0.46487806, -0.25316081]]),
 array([17.86008107,  1.32709403,  0.50628624]),
 array([[-0.45342865, -0.63462942, -0.62581783],
        [ 0.3774178 ,  0.4993747 , -0.77985942],
        [ 0.80743932, -0.58980539,  0.01308965]]))

In [144]:
lin.qr(a)

(array([[-0.12309149,  0.69631062, -0.70710678],
        [-0.49236596, -0.66149509, -0.56568542],
        [-0.86164044,  0.27852425,  0.42426407]]),
 array([[ -8.1240384 , -11.32441717, -11.07823419],
        [  0.        ,   0.87038828,   0.62667956],
        [  0.        ,   0.        ,  -1.69705627]]))

In [145]:
lin.lu(a)


(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]), array([[ 1.        ,  0.        ,  0.        ],
        [ 0.57142857,  1.        ,  0.        ],
        [ 0.14285714, -0.8       ,  1.        ]]), array([[ 7.        , 10.        ,  9.        ],
        [ 0.        , -0.71428571,  0.85714286],
        [ 0.        ,  0.        ,  2.4       ]]))

In [146]:
np.fft.fft(a)

array([[ 6. +0.j       , -1.5+0.8660254j, -1.5-0.8660254j],
       [15. +0.j       , -1.5+0.8660254j, -1.5-0.8660254j],
       [26. +0.j       , -2.5-0.8660254j, -2.5+0.8660254j]])

In [147]:
np.fft.ifft(a)

array([[ 2.        +0.j        , -0.5       -0.28867513j,
        -0.5       +0.28867513j],
       [ 5.        +0.j        , -0.5       -0.28867513j,
        -0.5       +0.28867513j],
       [ 8.66666667+0.j        , -0.83333333+0.28867513j,
        -0.83333333-0.28867513j]])

In [148]:
np.sort(a)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  9, 10]])

In [149]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
lin.lstsq(a, b)

(array([[ 1.00000000e+00,  5.00000000e-01,  2.13518294e-16],
        [ 1.06024281e-15,  5.55111512e-16, -3.33066907e-16],
        [ 1.38733298e-16,  5.00000000e-01,  1.00000000e+00]]),
 array([], dtype=float64),
 3,
 array([17.86008107,  1.32709403,  0.50628624]))

In [150]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])

In [151]:
a.squeeze()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 10,  9]])