In [452]:
import numpy as np
import scipy.linalg as lin

arr = np.array([1, 2, 3, 4, 5])

In [453]:
np.ndim(arr)

1

In [454]:
arr.size

5

In [455]:
arr.shape

(5,)

In [456]:
arr.shape[0]

5

In [457]:
arr2 = np.array([[1.,2.,3.], [4.,5.,6.]])

In [458]:
arr2.shape

(2, 3)

In [459]:
arr2.shape[0]

2

In [460]:
arr2.shape[1]

3

In [461]:
a = np.array([1.,2.,3.])
b = np.array([2.,3.,4.])
c = np.array([3.,4.,5.])
d = np.array([4.,5.,6.])

np.block([[a,b],[c,d]])

array([[1., 2., 3., 2., 3., 4.],
       [3., 4., 5., 4., 5., 6.]])

In [462]:
a[-1]

3.0

In [463]:
a[1:2]

array([2.])

In [464]:
a = np.array([[1.,2.,3.], [4.,5.,6.]])
a[1,:]

array([4., 5., 6.])

In [465]:
a[1]

array([4., 5., 6.])

In [466]:
a[np.ix_([0],[0])]

array([[1.]])

In [467]:
a[::2, :]

array([[1., 2., 3.]])

In [468]:
a[::-1,:]

array([[4., 5., 6.],
       [1., 2., 3.]])

In [469]:
a[np.r_[:len(a),0]]

array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [470]:
a.transpose()

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [471]:
a.conj().transpose()

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [472]:
a @ b

array([20., 47.])

In [473]:
a * b

array([[ 2.,  6., 12.],
       [ 8., 15., 24.]])

In [474]:
a / b

array([[0.5       , 0.66666667, 0.75      ],
       [2.        , 1.66666667, 1.5       ]])

In [475]:
a ** 3

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [476]:
(a>4)

array([[False, False, False],
       [False,  True,  True]])

In [477]:
np.nonzero(a>4)

(array([1, 1]), array([1, 2]))

In [478]:
a[a<0.5] = 0


In [479]:
a * (a > 0.5)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [480]:
a[:] = 3

In [481]:
a

array([[3., 3., 3.],
       [3., 3., 3.]])

In [482]:
b = a.copy()

In [483]:
a, b

(array([[3., 3., 3.],
        [3., 3., 3.]]), array([[3., 3., 3.],
        [3., 3., 3.]]))

In [484]:
b = a[1,:].copy()
b

array([3., 3., 3.])

In [485]:
b = a.flatten()
b

array([3., 3., 3., 3., 3., 3.])

In [486]:
np.arange(1., 11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [487]:
np.r_[1.,11.]

array([ 1., 11.])

In [488]:
np.r_[:9:10j]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [489]:
np.arange(1., 11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [490]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [491]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [492]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [493]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [494]:
np.diag(a)

array([3., 3.])

In [495]:
np.diag(a,0)

array([3., 3.])

In [496]:
np.random.rand(3,4)

array([[0.9105931 , 0.0302452 , 0.30197429, 0.11621356],
       [0.58361325, 0.10832207, 0.25991543, 0.89610134],
       [0.68533444, 0.1551064 , 0.85200121, 0.39677527]])

In [497]:
np.random.random_sample((3,4,5))

array([[[0.71993562, 0.5315764 , 0.86327692, 0.34137504, 0.93958448],
        [0.02117298, 0.62678233, 0.76586814, 0.51173745, 0.47639314],
        [0.12490906, 0.89673838, 0.94005931, 0.61407022, 0.95585806],
        [0.91773605, 0.89990596, 0.99991869, 0.11196143, 0.21447424]],

       [[0.46116823, 0.22438304, 0.67488583, 0.05119595, 0.33700133],
        [0.45776139, 0.67522112, 0.10333024, 0.7502323 , 0.05101259],
        [0.62416985, 0.94810824, 0.59906576, 0.96664816, 0.86967964],
        [0.38641564, 0.91139724, 0.60791232, 0.65281569, 0.32474003]],

       [[0.72022067, 0.03466243, 0.67709944, 0.34863602, 0.43359897],
        [0.85049027, 0.626914  , 0.76852082, 0.1893989 , 0.24599448],
        [0.33497361, 0.48731719, 0.99389728, 0.88765664, 0.05045839],
        [0.35632601, 0.73719812, 0.5549492 , 0.41391888, 0.82698607]]])

In [498]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [499]:
np.mgrid[0:9., 0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [500]:
np.ogrid[0:9., 0:6.]

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]])]

In [501]:
np.ix_(np.r_[0:9.], np.r_[0:6.])

(array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]]))

In [502]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]), array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [503]:
np.tile(a, (3,4))

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [504]:
np.concatenate((c,d),0)

array([3., 4., 5., 4., 5., 6.])

In [505]:
np.vstack((c,d))

array([[3., 4., 5.],
       [4., 5., 6.]])

In [506]:
d.max()

6.0

In [507]:
d.max(0)

6.0

In [508]:
a.max(1)

array([3., 3.])

In [509]:
np.maximum(c,d )

array([4., 5., 6.])

In [510]:
np.sqrt(c @ c)

7.0710678118654755

In [511]:
np.linalg.norm(c)

7.0710678118654755

In [512]:
np.logical_and(c,d)

array([ True,  True,  True])

In [513]:
np.logical_or(c,d)

array([ True,  True,  True])

In [514]:
a = np.array([[1, 2, 3], [4,5,6], [7,10,9]])

lin.eig(a)

(array([16.82540654+0.j, -0.56655283+0.j, -1.2588537 +0.j]),
 array([[-0.22187905, -0.86720234, -0.7307057 ],
        [-0.49983984,  0.47988984, -0.16747068],
        [-0.83721552,  0.13291287,  0.66183288]]))

In [515]:
lin.inv(a)

array([[-1.25      ,  1.        , -0.25      ],
       [ 0.5       , -1.        ,  0.5       ],
       [ 0.41666667,  0.33333333, -0.25      ]])

In [516]:
lin.pinv(a)

array([[-1.25      ,  1.        , -0.25      ],
       [ 0.5       , -1.        ,  0.5       ],
       [ 0.41666667,  0.33333333, -0.25      ]])

In [517]:
lin.solve(a, c)

array([-1.        , -0.        ,  1.33333333])

In [518]:
lin.svd(a)

(array([[-0.20157473, -0.72595537, -0.65753816],
        [-0.48945851, -0.50683053,  0.70961481],
        [-0.8484091 ,  0.46487806, -0.25316081]]),
 array([17.86008107,  1.32709403,  0.50628624]),
 array([[-0.45342865, -0.63462942, -0.62581783],
        [ 0.3774178 ,  0.4993747 , -0.77985942],
        [ 0.80743932, -0.58980539,  0.01308965]]))

In [519]:
lin.qr(a)

(array([[-0.12309149,  0.69631062, -0.70710678],
        [-0.49236596, -0.66149509, -0.56568542],
        [-0.86164044,  0.27852425,  0.42426407]]),
 array([[ -8.1240384 , -11.32441717, -11.07823419],
        [  0.        ,   0.87038828,   0.62667956],
        [  0.        ,   0.        ,  -1.69705627]]))

In [520]:
lin.lu(a)


(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]), array([[ 1.        ,  0.        ,  0.        ],
        [ 0.57142857,  1.        ,  0.        ],
        [ 0.14285714, -0.8       ,  1.        ]]), array([[ 7.        , 10.        ,  9.        ],
        [ 0.        , -0.71428571,  0.85714286],
        [ 0.        ,  0.        ,  2.4       ]]))

In [521]:
np.fft.fft(a)

array([[ 6. +0.j       , -1.5+0.8660254j, -1.5-0.8660254j],
       [15. +0.j       , -1.5+0.8660254j, -1.5-0.8660254j],
       [26. +0.j       , -2.5-0.8660254j, -2.5+0.8660254j]])

In [522]:
np.fft.ifft(a)

array([[ 2.        +0.j        , -0.5       -0.28867513j,
        -0.5       +0.28867513j],
       [ 5.        +0.j        , -0.5       -0.28867513j,
        -0.5       +0.28867513j],
       [ 8.66666667+0.j        , -0.83333333+0.28867513j,
        -0.83333333-0.28867513j]])

In [523]:
np.sort(a)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  9, 10]])

In [524]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
lin.lstsq(a, b)

(array([[ 1.00000000e+00,  5.00000000e-01,  2.13518294e-16],
        [ 1.06024281e-15,  5.55111512e-16, -3.33066907e-16],
        [ 1.38733298e-16,  5.00000000e-01,  1.00000000e+00]]),
 array([], dtype=float64),
 3,
 array([17.86008107,  1.32709403,  0.50628624]))

In [525]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])

In [526]:
a.squeeze()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 10,  9]])