In [302]:
import numpy as np
import scipy.linalg as lin

arr = np.array([1, 2, 3, 4, 5])

In [303]:
np.ndim(arr)

1

In [304]:
arr.size

5

In [305]:
arr.shape

(5,)

In [306]:
arr.shape[0]

5

In [307]:
arr2 = np.array([[1.,2.,3.], [4.,5.,6.]])

In [308]:
arr2.shape

(2, 3)

In [309]:
arr2.shape[0]

2

In [310]:
arr2.shape[1]

3

In [311]:
a = np.array([1.,2.,3.])
b = np.array([2.,3.,4.])
c = np.array([3.,4.,5.])
d = np.array([4.,5.,6.])

np.block([[a,b],[c,d]])

array([[1., 2., 3., 2., 3., 4.],
       [3., 4., 5., 4., 5., 6.]])

In [312]:
a[-1]

3.0

In [313]:
a[1:2]

array([2.])

In [314]:
a = np.array([[1.,2.,3.], [4.,5.,6.]])
a[1,:]

array([4., 5., 6.])

In [315]:
a[1]

array([4., 5., 6.])

In [316]:
a[np.ix_([0],[0])]

array([[1.]])

In [317]:
a[::2, :]

array([[1., 2., 3.]])

In [318]:
a[::-1,:]

array([[4., 5., 6.],
       [1., 2., 3.]])

In [319]:
a[np.r_[:len(a),0]]

array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [320]:
a.transpose()

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [321]:
a.conj().transpose()

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [322]:
a @ b

array([20., 47.])

In [323]:
a * b

array([[ 2.,  6., 12.],
       [ 8., 15., 24.]])

In [324]:
a / b

array([[0.5       , 0.66666667, 0.75      ],
       [2.        , 1.66666667, 1.5       ]])

In [325]:
a ** 3

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [326]:
(a>4)

array([[False, False, False],
       [False,  True,  True]])

In [327]:
np.nonzero(a>4)

(array([1, 1]), array([1, 2]))

In [328]:
a[a<0.5] = 0


In [329]:
a * (a > 0.5)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [330]:
a[:] = 3

In [331]:
a

array([[3., 3., 3.],
       [3., 3., 3.]])

In [332]:
b = a.copy()

In [333]:
a, b

(array([[3., 3., 3.],
        [3., 3., 3.]]), array([[3., 3., 3.],
        [3., 3., 3.]]))

In [334]:
b = a[1,:].copy()
b

array([3., 3., 3.])

In [335]:
b = a.flatten()
b

array([3., 3., 3., 3., 3., 3.])

In [336]:
np.arange(1., 11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [337]:
np.r_[1.,11.]

array([ 1., 11.])

In [338]:
np.r_[:9:10j]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [339]:
np.arange(1., 11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [340]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [341]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [342]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [343]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [344]:
np.diag(a)

array([3., 3.])

In [345]:
np.diag(a,0)

array([3., 3.])

In [346]:
np.random.rand(3,4)

array([[0.33517933, 0.45817287, 0.91628292, 0.13132187],
       [0.15300292, 0.31659406, 0.08347966, 0.95557442],
       [0.3764453 , 0.07451354, 0.69651202, 0.36601217]])

In [347]:
np.random.random_sample((3,4,5))

array([[[0.28437125, 0.28584188, 0.20558395, 0.74564525, 0.40481449],
        [0.06293774, 0.18869119, 0.7738074 , 0.80609558, 0.96069379],
        [0.66884459, 0.47035081, 0.23707714, 0.13633062, 0.16714204],
        [0.4445503 , 0.54793019, 0.04218509, 0.31243873, 0.95785538]],

       [[0.1711811 , 0.4114149 , 0.61061959, 0.4762228 , 0.18563047],
        [0.87626597, 0.72852526, 0.14808285, 0.37999467, 0.22452616],
        [0.49858488, 0.30185628, 0.64124686, 0.29869931, 0.27458252],
        [0.81612102, 0.17041924, 0.54921654, 0.27957175, 0.36970019]],

       [[0.77632619, 0.42713843, 0.58236882, 0.56837975, 0.27786976],
        [0.04922684, 0.739664  , 0.34509393, 0.07673217, 0.43570471],
        [0.05892963, 0.04850176, 0.35308205, 0.99770686, 0.19489782],
        [0.70102481, 0.90253416, 0.78590844, 0.62478003, 0.52046895]]])

In [348]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [349]:
np.mgrid[0:9., 0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [350]:
np.ogrid[0:9., 0:6.]

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]])]

In [351]:
np.ix_(np.r_[0:9.], np.r_[0:6.])

(array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]]))

In [352]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]), array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [353]:
np.tile(a, (3,4))

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [354]:
np.concatenate((c,d),0)

array([3., 4., 5., 4., 5., 6.])

In [355]:
np.vstack((c,d))

array([[3., 4., 5.],
       [4., 5., 6.]])

In [356]:
d.max()

6.0

In [357]:
d.max(0)

6.0

In [358]:
a.max(1)

array([3., 3.])

In [359]:
np.maximum(c,d )

array([4., 5., 6.])

In [360]:
np.sqrt(c @ c)

7.0710678118654755

In [361]:
np.linalg.norm(c)

7.0710678118654755

In [362]:
np.logical_and(c,d)

array([ True,  True,  True])

In [363]:
np.logical_or(c,d)

array([ True,  True,  True])

In [364]:
a = np.array([[1, 2, 3], [4,5,6], [7,10,9]])

lin.eig(a)

(array([16.82540654+0.j, -0.56655283+0.j, -1.2588537 +0.j]),
 array([[-0.22187905, -0.86720234, -0.7307057 ],
        [-0.49983984,  0.47988984, -0.16747068],
        [-0.83721552,  0.13291287,  0.66183288]]))

In [365]:
lin.inv(a)

array([[-1.25      ,  1.        , -0.25      ],
       [ 0.5       , -1.        ,  0.5       ],
       [ 0.41666667,  0.33333333, -0.25      ]])

In [366]:
lin.pinv(a)

array([[-1.25      ,  1.        , -0.25      ],
       [ 0.5       , -1.        ,  0.5       ],
       [ 0.41666667,  0.33333333, -0.25      ]])

In [367]:
lin.solve(a, c)

array([-1.        , -0.        ,  1.33333333])

In [368]:
lin.svd(a)

(array([[-0.20157473, -0.72595537, -0.65753816],
        [-0.48945851, -0.50683053,  0.70961481],
        [-0.8484091 ,  0.46487806, -0.25316081]]),
 array([17.86008107,  1.32709403,  0.50628624]),
 array([[-0.45342865, -0.63462942, -0.62581783],
        [ 0.3774178 ,  0.4993747 , -0.77985942],
        [ 0.80743932, -0.58980539,  0.01308965]]))

In [369]:
lin.qr(a)

(array([[-0.12309149,  0.69631062, -0.70710678],
        [-0.49236596, -0.66149509, -0.56568542],
        [-0.86164044,  0.27852425,  0.42426407]]),
 array([[ -8.1240384 , -11.32441717, -11.07823419],
        [  0.        ,   0.87038828,   0.62667956],
        [  0.        ,   0.        ,  -1.69705627]]))

In [370]:
lin.lu(a)


(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]), array([[ 1.        ,  0.        ,  0.        ],
        [ 0.57142857,  1.        ,  0.        ],
        [ 0.14285714, -0.8       ,  1.        ]]), array([[ 7.        , 10.        ,  9.        ],
        [ 0.        , -0.71428571,  0.85714286],
        [ 0.        ,  0.        ,  2.4       ]]))

In [371]:
np.fft.fft(a)

array([[ 6. +0.j       , -1.5+0.8660254j, -1.5-0.8660254j],
       [15. +0.j       , -1.5+0.8660254j, -1.5-0.8660254j],
       [26. +0.j       , -2.5-0.8660254j, -2.5+0.8660254j]])

In [372]:
np.fft.ifft(a)

array([[ 2.        +0.j        , -0.5       -0.28867513j,
        -0.5       +0.28867513j],
       [ 5.        +0.j        , -0.5       -0.28867513j,
        -0.5       +0.28867513j],
       [ 8.66666667+0.j        , -0.83333333+0.28867513j,
        -0.83333333-0.28867513j]])

In [373]:
np.sort(a)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  9, 10]])

In [374]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
lin.lstsq(a, b)

(array([[ 1.00000000e+00,  5.00000000e-01,  2.13518294e-16],
        [ 1.06024281e-15,  5.55111512e-16, -3.33066907e-16],
        [ 1.38733298e-16,  5.00000000e-01,  1.00000000e+00]]),
 array([], dtype=float64),
 3,
 array([17.86008107,  1.32709403,  0.50628624]))

In [375]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])

In [376]:
a.squeeze()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 10,  9]])